### ISSUE TITLE
Why no cjs in npm package?

### ISSUE THREAD

**Issue by madbbb** [CleverCloud/clever-client.js#39]
How do you use it in NodeJS?

**Comment by hsablonniere** [comment]
Hi @madbbb, have you looked at this? Does it help?

**Comment by madbbb** [comment]
Thank you for your quick response @hsablonniere. Sorry my bad

**Comment by hsablonniere** [comment]
@madbbb Sure, no problem, I was worried that maybe something was broken and prevented you from using it :wink:
