### ISSUE TITLE
ApplicationLogStream: Browser users would like to know the state of `retryCount` when errors occur

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-client.js#95]
We see 3 solutions:

1. Add a `retryCount` property on the `event` object of `onError` event
2. Rename the object `_retryCount` property to `retryCount` so it's public
3. Pass the `retryCount` as a new param of the `onError` callback

We prefer solution (2) as it's the most ubiquitous.

* Solution (1) is not that bad for the browser use case but you don't get the fact that the retryCount is reset (or not) when receiving the new message
* Solution (3) is weird because of the `EventTarget`/`EventEmitter` contract, callbacks only get one param

**Comment by miton18** [comment]
Agreed on solution 2,

But, can we have the use case ? for which purpose, the user want to know the retry count ?
